export const PIGGY_BANK_VAULT_ADDRESS =
  process.env.REACT_APP_PIGGY_BANK_VAULT_CONTRACT_ADDRESS || '';
export const PIGGY_FRENS_CONTRACT_ADDRESS =
  process.env.REACT_APP_PIGGY_FRENS_CONTRACT_ADDRESS || '';
export const QUEST_SESSION_STORAGE_KEY=
    "QUEST"
export const PIGGY_BANK_BALANCE=
    "PIGGY_BANK_BALANCE"