export const PIGGY_BANK_VAULT_ADDRESS =
  process.env.REACT_APP_PIGGY_BANK_VAULT_CONTRACT_ADDRESS || '';
export const PIGGY_FREN_CONTRACT_ADDRESS = process.env.REACT_APP_PIGGY_FREN_CONTRACT_ADDRESS || '';
